{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.6.1-rc.2/sdk-1.6.1-rc.2.module",
    "group": "com.loopmediagroup.client",
    "module": "sdk",
    "version": "1.6.1-rc.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "7wsggru4rfhn7ledh5em7jaoai"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.6.1-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.6.1-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.6.1-rc.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.6.1-rc.2.aar",
          "size": 1664308,
          "sha512": "bf038b2e65102a9b011f2ade61aa9f0f663f38fd2761ac2c8a5f9f014a5475c1b0075eb4be89445ba402f1969403dfedb8e30f935d4d78ffbcc04d5a20cf13df",
          "sha256": "0968b367ac8b4b78d7d6f7479f4967b659874feb4305e3e2fd25e23491c84964",
          "sha1": "4ae572d45ddabdf6f0948198d3467d2aa52e2ba0",
          "md5": "5e39440604f06040772e91085b8a86a3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.6.1-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.6.1-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.6.1-rc.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "data-access",
          "version": {
            "requires": "1.6.1-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "remote-data",
          "version": {
            "requires": "1.6.1-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "local-data",
          "version": {
            "requires": "1.6.1-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sensor-data",
          "version": {
            "requires": "1.6.1-rc.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.6.1-rc.2.aar",
          "size": 1664308,
          "sha512": "bf038b2e65102a9b011f2ade61aa9f0f663f38fd2761ac2c8a5f9f014a5475c1b0075eb4be89445ba402f1969403dfedb8e30f935d4d78ffbcc04d5a20cf13df",
          "sha256": "0968b367ac8b4b78d7d6f7479f4967b659874feb4305e3e2fd25e23491c84964",
          "sha1": "4ae572d45ddabdf6f0948198d3467d2aa52e2ba0",
          "md5": "5e39440604f06040772e91085b8a86a3"
        }
      ]
    }
  ]
}
