{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.6.1-rc.3/sdk-1.6.1-rc.3.module",
    "group": "com.loopmediagroup.client",
    "module": "sdk",
    "version": "1.6.1-rc.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "bjrwyd56rfar7d4er2dysitvhq"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.6.1-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.6.1-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.6.1-rc.3"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.6.1-rc.3.aar",
          "size": 1664232,
          "sha512": "32e25fa367cf5efbb449c2e181b434bad6f565a49edd88a64dafa7f6955af866f5c20bbeeb53d827628ed84e8ac327e6da4871bac676fd59258c5ebc378e43e9",
          "sha256": "1c9638d1c177aa8c3fe7988d05d7b9a64a80975b6a5ecd185f3d2f9e22a505b0",
          "sha1": "3b9f037c90b490aefaf79ee0f25224605597755d",
          "md5": "b9f8c815b421fe9b0462eb5e1c05561c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.6.1-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.6.1-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.6.1-rc.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "data-access",
          "version": {
            "requires": "1.6.1-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "remote-data",
          "version": {
            "requires": "1.6.1-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "local-data",
          "version": {
            "requires": "1.6.1-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sensor-data",
          "version": {
            "requires": "1.6.1-rc.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.6.1-rc.3.aar",
          "size": 1664232,
          "sha512": "32e25fa367cf5efbb449c2e181b434bad6f565a49edd88a64dafa7f6955af866f5c20bbeeb53d827628ed84e8ac327e6da4871bac676fd59258c5ebc378e43e9",
          "sha256": "1c9638d1c177aa8c3fe7988d05d7b9a64a80975b6a5ecd185f3d2f9e22a505b0",
          "sha1": "3b9f037c90b490aefaf79ee0f25224605597755d",
          "md5": "b9f8c815b421fe9b0462eb5e1c05561c"
        }
      ]
    }
  ]
}
