{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.9.0-rc.1/sdk-1.9.0-rc.1.module",
    "group": "com.loopmediagroup.client",
    "module": "sdk",
    "version": "1.9.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "pdbrm5u3wzc3zegc23i6cfs6la"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.9.0-rc.1.aar",
          "size": 1776166,
          "sha512": "6f93bdddfdc3321eff450810da34b95f872d06355d4acc86a6daac8779050201ae93ef29df81390308f088f6713828279f20d13d9168de8a1e570329e6d220a0",
          "sha256": "33b91c65d3fa7b609041151daedf5f5ee19f01092c20112c67d646fb187c76e3",
          "sha1": "e6fead8a764dc6f47085ee2a182d0dba97da158f",
          "md5": "3648f0b396928f8117d32861d6030b61"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "data-access",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "remote-data",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "local-data",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sensor-data",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.9.0-rc.1.aar",
          "size": 1776166,
          "sha512": "6f93bdddfdc3321eff450810da34b95f872d06355d4acc86a6daac8779050201ae93ef29df81390308f088f6713828279f20d13d9168de8a1e570329e6d220a0",
          "sha256": "33b91c65d3fa7b609041151daedf5f5ee19f01092c20112c67d646fb187c76e3",
          "sha1": "e6fead8a764dc6f47085ee2a182d0dba97da158f",
          "md5": "3648f0b396928f8117d32861d6030b61"
        }
      ]
    }
  ]
}
