{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.9.0-rc.1/sdk-1.9.0-rc.1.module",
    "group": "com.loopmediagroup.client",
    "module": "sdk",
    "version": "1.9.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ztxesydrrjdfrjcaly7gr4e634"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.9.0-rc.1.aar",
          "size": 1775213,
          "sha512": "c10756c8a72cb52d4aecb11d5688a9293dcee236129c155ed3a40d1035e7f8e6be69652481cc2095aab22a52d246b3fe0e262248da365c8182ef85042ec43706",
          "sha256": "f304018cb47f49797e25e879859cb263c750a4b25746f9e983c451c8eacb2189",
          "sha1": "73deca7ad596e616351504a6423d0cf754a18737",
          "md5": "55a34b66ff0aa0718353bbf257583ae8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "data-access",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "remote-data",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "local-data",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sensor-data",
          "version": {
            "requires": "1.9.0-rc.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.9.0-rc.1.aar",
          "size": 1775213,
          "sha512": "c10756c8a72cb52d4aecb11d5688a9293dcee236129c155ed3a40d1035e7f8e6be69652481cc2095aab22a52d246b3fe0e262248da365c8182ef85042ec43706",
          "sha256": "f304018cb47f49797e25e879859cb263c750a4b25746f9e983c451c8eacb2189",
          "sha1": "73deca7ad596e616351504a6423d0cf754a18737",
          "md5": "55a34b66ff0aa0718353bbf257583ae8"
        }
      ]
    }
  ]
}
