{
  "formatVersion": "1.1",
  "component": {
    "group": "com.loopmediagroup.client",
    "module": "android-ui",
    "version": "1.6.1-10179",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "2skg7d7u65gkpgbwvm3qta2fem"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "library",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "adapters",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-1.6.1-10179.aar",
          "url": "android-ui-1.6.1-10179.aar",
          "size": 1418934,
          "sha512": "70f5be7c779939f977adb97147bc4873cb6cabca1ddce6bf3a7811a3637f1c0794e67f250799c725aea6e5ca43f75b8edf935e229f81e4101763bb521b76ffb4",
          "sha256": "1d90b68bdb4baa473817fd33b11f5a03c86e0b1de30dc1d6f94b39585c845a07",
          "sha1": "349d4f9ee10c70e4057237b71c02f50cf1a4ecf8",
          "md5": "b677add2c12fd1c23928d3dfbf1f0e17"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "library",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "adapters",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sdk",
          "version": {
            "requires": "1.6.1-rc.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-v4",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "recyclerview-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "cardview-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "design",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support.constraint",
          "module": "constraint-layout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "android.arch.lifecycle",
          "module": "extensions",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "15.0.1"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "android-maps-utils",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.hannesdorfmann",
          "module": "adapterdelegates3",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "nl.dionsegijn",
          "module": "konfetti",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-1.6.1-10179.aar",
          "url": "android-ui-1.6.1-10179.aar",
          "size": 1418934,
          "sha512": "70f5be7c779939f977adb97147bc4873cb6cabca1ddce6bf3a7811a3637f1c0794e67f250799c725aea6e5ca43f75b8edf935e229f81e4101763bb521b76ffb4",
          "sha256": "1d90b68bdb4baa473817fd33b11f5a03c86e0b1de30dc1d6f94b39585c845a07",
          "sha1": "349d4f9ee10c70e4057237b71c02f50cf1a4ecf8",
          "md5": "b677add2c12fd1c23928d3dfbf1f0e17"
        }
      ]
    }
  ]
}
