{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.7.0-rc.2/sdk-1.7.0-rc.2.module",
    "group": "com.loopmediagroup.client",
    "module": "sdk",
    "version": "1.7.0-rc.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "oc2jzcohmrbhzpcj6t4nc36zuu"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.7.0-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.7.0-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.7.0-rc.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.7.0-rc.2.aar",
          "size": 1753078,
          "sha512": "d2ac7e36628ba8a49013b6803d28c64af33103037713f2b0ee20c84b812c4d72e23d2186018fd08afdd5845b6fe70a3987c99845a02d4f9d38282875968a34bd",
          "sha256": "74d311257dd3fc4fc80b01b10d8ed105653ddf040fff519d9688e0771e85d673",
          "sha1": "8930de12415aa985c390ee75c1e6a956128a1ead",
          "md5": "9e2c2ec8158020402829efa08ae33513"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.7.0-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.7.0-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.7.0-rc.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "data-access",
          "version": {
            "requires": "1.7.0-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "remote-data",
          "version": {
            "requires": "1.7.0-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "local-data",
          "version": {
            "requires": "1.7.0-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sensor-data",
          "version": {
            "requires": "1.7.0-rc.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.7.0-rc.2.aar",
          "size": 1753078,
          "sha512": "d2ac7e36628ba8a49013b6803d28c64af33103037713f2b0ee20c84b812c4d72e23d2186018fd08afdd5845b6fe70a3987c99845a02d4f9d38282875968a34bd",
          "sha256": "74d311257dd3fc4fc80b01b10d8ed105653ddf040fff519d9688e0771e85d673",
          "sha1": "8930de12415aa985c390ee75c1e6a956128a1ead",
          "md5": "9e2c2ec8158020402829efa08ae33513"
        }
      ]
    }
  ]
}
