{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.7.0-rc.3/sdk-1.7.0-rc.3.module",
    "group": "com.loopmediagroup.client",
    "module": "sdk",
    "version": "1.7.0-rc.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "r24hlleyfnb6bhn6x3cf42vegq"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.7.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.7.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.7.0-rc.3"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.7.0-rc.3.aar",
          "size": 1753138,
          "sha512": "a2be4ed78f2b58ee1f32a12cf07201f6b28b6b12c15188b55566ed9aef51e3926e35ca7e9fd104db32851986faf98adef6b4844856af3c86bc839fb60cb87260",
          "sha256": "475c775e76307ea2f7a7028afad671301207058f8c040e59e73683f66649a02e",
          "sha1": "8b33857eb1e842042fca16a501c3d8fd52c6d4bb",
          "md5": "34197df4f301ea920a570d5c8b77c895"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.7.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.7.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.7.0-rc.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "data-access",
          "version": {
            "requires": "1.7.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "remote-data",
          "version": {
            "requires": "1.7.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "local-data",
          "version": {
            "requires": "1.7.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sensor-data",
          "version": {
            "requires": "1.7.0-rc.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.7.0-rc.3.aar",
          "size": 1753138,
          "sha512": "a2be4ed78f2b58ee1f32a12cf07201f6b28b6b12c15188b55566ed9aef51e3926e35ca7e9fd104db32851986faf98adef6b4844856af3c86bc839fb60cb87260",
          "sha256": "475c775e76307ea2f7a7028afad671301207058f8c040e59e73683f66649a02e",
          "sha1": "8b33857eb1e842042fca16a501c3d8fd52c6d4bb",
          "md5": "34197df4f301ea920a570d5c8b77c895"
        }
      ]
    }
  ]
}
