{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.6.2-rc.1/sdk-1.6.2-rc.1.module",
    "group": "com.loopmediagroup.client",
    "module": "sdk",
    "version": "1.6.2-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "mb6z5lt5gza4piqdf3wnpo3r6m"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.6.2-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.6.2-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.6.2-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.6.2-rc.1.aar",
          "size": 1671729,
          "sha512": "2cd3d1ced88ea60f7e565c3ef2a0619310d64963dee46be11976e81a64ff119c6e6d451310e85a2d1f01d8a6459633526ccd14e4457222784bdbb869a7652516",
          "sha256": "0f87cbea6f31af6da8486cbce076a39ca682bbe68d9585f358e35a708965bfb6",
          "sha1": "cab0b33d58f8459a33682a04ce164a64232784e2",
          "md5": "26333ec06f5ebbf5ae58c6bee154a85a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.6.2-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.6.2-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.6.2-rc.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "data-access",
          "version": {
            "requires": "1.6.2-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "remote-data",
          "version": {
            "requires": "1.6.2-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "local-data",
          "version": {
            "requires": "1.6.2-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sensor-data",
          "version": {
            "requires": "1.6.2-rc.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.6.2-rc.1.aar",
          "size": 1671729,
          "sha512": "2cd3d1ced88ea60f7e565c3ef2a0619310d64963dee46be11976e81a64ff119c6e6d451310e85a2d1f01d8a6459633526ccd14e4457222784bdbb869a7652516",
          "sha256": "0f87cbea6f31af6da8486cbce076a39ca682bbe68d9585f358e35a708965bfb6",
          "sha1": "cab0b33d58f8459a33682a04ce164a64232784e2",
          "md5": "26333ec06f5ebbf5ae58c6bee154a85a"
        }
      ]
    }
  ]
}
