{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/2.0.0-rc.3/sdk-2.0.0-rc.3.module",
    "group": "com.loopmediagroup.client",
    "module": "sdk",
    "version": "2.0.0-rc.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "5r5joe3bcffznj2ok36qe5xnuy"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "2.0.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "2.0.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "2.0.0-rc.3"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-2.0.0-rc.3.aar",
          "size": 1771805,
          "sha512": "ba753075ad8be66a5406aad2252505f1cddef8ad9b8551d12a4ccb55318a8f964a6fe3b0be16ae219359d3b6a34a7d8c8aa845b0ead8d1c02130bd04447d8482",
          "sha256": "9c58c0eec51f40ca33333e39d18e34c1db8e582ce6f53e7af067b7de9fd75b50",
          "sha1": "68b56200f143eca2fe74fdd7d71028153a3d480f",
          "md5": "f8729b262889c08f21ab9201f5986d9d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "2.0.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "2.0.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "2.0.0-rc.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "data-access",
          "version": {
            "requires": "2.0.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "remote-data",
          "version": {
            "requires": "2.0.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "local-data",
          "version": {
            "requires": "2.0.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sensor-data",
          "version": {
            "requires": "2.0.0-rc.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-2.0.0-rc.3.aar",
          "size": 1771805,
          "sha512": "ba753075ad8be66a5406aad2252505f1cddef8ad9b8551d12a4ccb55318a8f964a6fe3b0be16ae219359d3b6a34a7d8c8aa845b0ead8d1c02130bd04447d8482",
          "sha256": "9c58c0eec51f40ca33333e39d18e34c1db8e582ce6f53e7af067b7de9fd75b50",
          "sha1": "68b56200f143eca2fe74fdd7d71028153a3d480f",
          "md5": "f8729b262889c08f21ab9201f5986d9d"
        }
      ]
    }
  ]
}
