{
  "formatVersion": "1.1",
  "component": {
    "group": "com.loopmediagroup.client",
    "module": "android-ui",
    "version": "1.7.0-11044",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "tclggamd6vgqbaotckeubam2ou"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "library",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "adapters",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-1.7.0-11044.aar",
          "url": "android-ui-1.7.0-11044.aar",
          "size": 1368324,
          "sha512": "69c96cf13039a00dfbfb52326c72571c2c4fddcc27948b3a417c5c6717a0935958f9573facc6234e3757ae6e4da50150381447865183077f155ef18aebda8289",
          "sha256": "8e41ab3f7c34ef22a76e90fe23482c477810ac0dbd02e7b64e74349e46c35ed4",
          "sha1": "a1cdc1ef236c3d6159f7c09b5a6d3c6e796f2d72",
          "md5": "2e5ffd1a99304fb9f35d3626292e1d9c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "library",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "adapters",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sdk",
          "version": {
            "requires": "1.6.1-rc.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-v4",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "recyclerview-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "cardview-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "design",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support.constraint",
          "module": "constraint-layout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "android.arch.lifecycle",
          "module": "extensions",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "15.0.1"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "android-maps-utils",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.hannesdorfmann",
          "module": "adapterdelegates3",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "nl.dionsegijn",
          "module": "konfetti",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-1.7.0-11044.aar",
          "url": "android-ui-1.7.0-11044.aar",
          "size": 1368324,
          "sha512": "69c96cf13039a00dfbfb52326c72571c2c4fddcc27948b3a417c5c6717a0935958f9573facc6234e3757ae6e4da50150381447865183077f155ef18aebda8289",
          "sha256": "8e41ab3f7c34ef22a76e90fe23482c477810ac0dbd02e7b64e74349e46c35ed4",
          "sha1": "a1cdc1ef236c3d6159f7c09b5a6d3c6e796f2d72",
          "md5": "2e5ffd1a99304fb9f35d3626292e1d9c"
        }
      ]
    }
  ]
}
