{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/2.0.0-rc.5/sdk-2.0.0-rc.5.module",
    "group": "com.loopmediagroup.client",
    "module": "sdk",
    "version": "2.0.0-rc.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "5ax3rkflwreqpp2cvriyzz4rsi"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "2.0.0-rc.5"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "2.0.0-rc.5"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "2.0.0-rc.5"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-2.0.0-rc.5.aar",
          "size": 1772882,
          "sha512": "4e47f01a09297dd2bf248ea77ab2ae21d0ebec6e4ab0b50d196311717569dfbdc7ebf3544b9261a97eab58ebece82344efcdda6cf62b4d89bb5ff8063c624f49",
          "sha256": "cb8e4c67ab5bbba0461b151b9e3d0fb6be92a9c02a57b1b5a1bf7c6440d347b7",
          "sha1": "fd372b03f2ca4a6ebeaa7e55371231d8a313a73f",
          "md5": "93fa5d37259867fa3a178e077563bcf5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "2.0.0-rc.5"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "2.0.0-rc.5"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "2.0.0-rc.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "data-access",
          "version": {
            "requires": "2.0.0-rc.5"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "remote-data",
          "version": {
            "requires": "2.0.0-rc.5"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "local-data",
          "version": {
            "requires": "2.0.0-rc.5"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sensor-data",
          "version": {
            "requires": "2.0.0-rc.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-2.0.0-rc.5.aar",
          "size": 1772882,
          "sha512": "4e47f01a09297dd2bf248ea77ab2ae21d0ebec6e4ab0b50d196311717569dfbdc7ebf3544b9261a97eab58ebece82344efcdda6cf62b4d89bb5ff8063c624f49",
          "sha256": "cb8e4c67ab5bbba0461b151b9e3d0fb6be92a9c02a57b1b5a1bf7c6440d347b7",
          "sha1": "fd372b03f2ca4a6ebeaa7e55371231d8a313a73f",
          "md5": "93fa5d37259867fa3a178e077563bcf5"
        }
      ]
    }
  ]
}
