{
  "formatVersion": "1.1",
  "component": {
    "group": "com.loopmediagroup.client",
    "module": "android-ui",
    "version": "2.0.0-rc.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "76zdfokdyjazlb6jrevtbddj34"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "library",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "adapters",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-2.0.0-rc.7.aar",
          "url": "android-ui-2.0.0-rc.7.aar",
          "size": 1371356,
          "sha512": "e74bd366576da8a2b3ffa6c792f50e69e5ee2908badad119f0718c4d028cda0871ad5a1b42f897ff0e962f1028dd82e03a8960669114e265765f697994860ec1",
          "sha256": "c3940b57268918d5a035b287f0a2b6dc5553012d1fa960b9f8cdd5151510666e",
          "sha1": "44d62ab01736b5d163e93cb27e75b2cd6175a723",
          "md5": "15372ccdad731ecd699fe723fc86ba13"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "library",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "adapters",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sdk",
          "version": {
            "requires": "2.0.0-rc.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-v4",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "recyclerview-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "cardview-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "design",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support.constraint",
          "module": "constraint-layout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "android.arch.lifecycle",
          "module": "extensions",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "15.0.1"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "android-maps-utils",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.hannesdorfmann",
          "module": "adapterdelegates3",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "nl.dionsegijn",
          "module": "konfetti",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-2.0.0-rc.7.aar",
          "url": "android-ui-2.0.0-rc.7.aar",
          "size": 1371356,
          "sha512": "e74bd366576da8a2b3ffa6c792f50e69e5ee2908badad119f0718c4d028cda0871ad5a1b42f897ff0e962f1028dd82e03a8960669114e265765f697994860ec1",
          "sha256": "c3940b57268918d5a035b287f0a2b6dc5553012d1fa960b9f8cdd5151510666e",
          "sha1": "44d62ab01736b5d163e93cb27e75b2cd6175a723",
          "md5": "15372ccdad731ecd699fe723fc86ba13"
        }
      ]
    }
  ]
}
