{
  "formatVersion": "1.1",
  "component": {
    "group": "com.loopmediagroup.client",
    "module": "android-ui",
    "version": "1.6.1-10066",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "2cdombo4srh45aet7lv5f77qaa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "library",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "adapters",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-1.6.1-10066.aar",
          "url": "android-ui-1.6.1-10066.aar",
          "size": 1418939,
          "sha512": "d7a1927fe3b640fdf9cb13338e420a89b50cfd1bad24e90bc2551326c4fe38b28ae8f22b1f246f7b26035ab760edfa822e35977218d608bdbd404fad68401bce",
          "sha256": "dea3c0500fc2c60aa41c577de09d6661d420c8b17e0966af0683c2fa9afdb548",
          "sha1": "4a5bae0477db78b7b315f4ebf674b0176da46599",
          "md5": "c9effabaeda4b1f0b35c6226c709794b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "library",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "adapters",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sdk",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-v4",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "recyclerview-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "cardview-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "design",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support.constraint",
          "module": "constraint-layout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "android.arch.lifecycle",
          "module": "extensions",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "15.0.1"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "android-maps-utils",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.hannesdorfmann",
          "module": "adapterdelegates3",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "nl.dionsegijn",
          "module": "konfetti",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-1.6.1-10066.aar",
          "url": "android-ui-1.6.1-10066.aar",
          "size": 1418939,
          "sha512": "d7a1927fe3b640fdf9cb13338e420a89b50cfd1bad24e90bc2551326c4fe38b28ae8f22b1f246f7b26035ab760edfa822e35977218d608bdbd404fad68401bce",
          "sha256": "dea3c0500fc2c60aa41c577de09d6661d420c8b17e0966af0683c2fa9afdb548",
          "sha1": "4a5bae0477db78b7b315f4ebf674b0176da46599",
          "md5": "c9effabaeda4b1f0b35c6226c709794b"
        }
      ]
    }
  ]
}
