{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.6.2-rc.2/sdk-1.6.2-rc.2.module",
    "group": "com.loopmediagroup.client",
    "module": "sdk",
    "version": "1.6.2-rc.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "c77s2xux2ffwvgkv6sn7lon6bi"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.6.2-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.6.2-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.6.2-rc.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.6.2-rc.2.aar",
          "size": 1671764,
          "sha512": "e9a62b126ede5b535a8c89ad2d68f1a0435f3d273db9641ab5e081083141387087162fa16849ad69bf849a75620a3519b4a7b740035f3864146bd149ff78e3b7",
          "sha256": "41f6db30b8654a7c3b40bac241baff60fb9ecac19ca1999228472bfa53f68f88",
          "sha1": "0ea3398f07a066618840b832d20da01bfc80b623",
          "md5": "1a780cb48959d7467276b014e175bce0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.6.2-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.6.2-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.6.2-rc.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "data-access",
          "version": {
            "requires": "1.6.2-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "remote-data",
          "version": {
            "requires": "1.6.2-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "local-data",
          "version": {
            "requires": "1.6.2-rc.2"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sensor-data",
          "version": {
            "requires": "1.6.2-rc.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.6.2-rc.2.aar",
          "size": 1671764,
          "sha512": "e9a62b126ede5b535a8c89ad2d68f1a0435f3d273db9641ab5e081083141387087162fa16849ad69bf849a75620a3519b4a7b740035f3864146bd149ff78e3b7",
          "sha256": "41f6db30b8654a7c3b40bac241baff60fb9ecac19ca1999228472bfa53f68f88",
          "sha1": "0ea3398f07a066618840b832d20da01bfc80b623",
          "md5": "1a780cb48959d7467276b014e175bce0"
        }
      ]
    }
  ]
}
