{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.6.1-rc.1/sdk-1.6.1-rc.1.module",
    "group": "com.loopmediagroup.client",
    "module": "sdk",
    "version": "1.6.1-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "spm5kzeu4jhqznt62xuhkpfc44"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.6.1-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.6.1-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.6.1-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.6.1-rc.1.aar",
          "size": 1659599,
          "sha512": "e48077af3e6a2b6d827686819f4c73aa258ce2692627b641a2d76cd3fda9974746284849a7ecd46737bd209b9afb4b3dbc2b83a33c7d87fe79ac789a383f8027",
          "sha256": "5336ac47bf5e10cb807077611a9957bfa4c8415fac7586f7e5f32b298287648a",
          "sha1": "0ea267b89a48f0dc07a03ab154ddb3851f49c8ea",
          "md5": "c93741187ba19191261d70aedc40d21f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.6.1-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.6.1-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.6.1-rc.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "data-access",
          "version": {
            "requires": "1.6.1-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "remote-data",
          "version": {
            "requires": "1.6.1-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "local-data",
          "version": {
            "requires": "1.6.1-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sensor-data",
          "version": {
            "requires": "1.6.1-rc.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.6.1-rc.1.aar",
          "size": 1659599,
          "sha512": "e48077af3e6a2b6d827686819f4c73aa258ce2692627b641a2d76cd3fda9974746284849a7ecd46737bd209b9afb4b3dbc2b83a33c7d87fe79ac789a383f8027",
          "sha256": "5336ac47bf5e10cb807077611a9957bfa4c8415fac7586f7e5f32b298287648a",
          "sha1": "0ea267b89a48f0dc07a03ab154ddb3851f49c8ea",
          "md5": "c93741187ba19191261d70aedc40d21f"
        }
      ]
    }
  ]
}
