{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.9.0-rc.3/sdk-1.9.0-rc.3.module",
    "group": "com.loopmediagroup.client",
    "module": "sdk",
    "version": "1.9.0-rc.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ttg7a2wmc5cj3cseyz4rozkzsq"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.9.0-rc.3.aar",
          "size": 1776128,
          "sha512": "781c97c61a8e91ab2aaeeb437b07b1a5b8a29fb3f20d2f8d9d784b2e4e7075a34c63420196357a0742c9eb5b857856a66de1d63f3ed5bd8a2d4897fb10554224",
          "sha256": "30d285f1746f9724a1b010c2c171e16e55048fd60e364d20860861b0722484ec",
          "sha1": "df30f999b1087c61e0f5c633f69737dff3f0c30f",
          "md5": "e99023c557143482f474a98fce69ddf4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "data-access",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "remote-data",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "local-data",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sensor-data",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.9.0-rc.3.aar",
          "size": 1776128,
          "sha512": "781c97c61a8e91ab2aaeeb437b07b1a5b8a29fb3f20d2f8d9d784b2e4e7075a34c63420196357a0742c9eb5b857856a66de1d63f3ed5bd8a2d4897fb10554224",
          "sha256": "30d285f1746f9724a1b010c2c171e16e55048fd60e364d20860861b0722484ec",
          "sha1": "df30f999b1087c61e0f5c633f69737dff3f0c30f",
          "md5": "e99023c557143482f474a98fce69ddf4"
        }
      ]
    }
  ]
}
