{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.9.0-rc.3/sdk-1.9.0-rc.3.module",
    "group": "com.loopmediagroup.client",
    "module": "sdk",
    "version": "1.9.0-rc.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "avygj6lm2rg7vjsbnvelqnrrou"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.9.0-rc.3.aar",
          "size": 1776133,
          "sha512": "230e5c367bc5edd24ac7d8e6579615f7c13e550bc84f50d832e1d66809e48bd3b4708d94ff9bc9fe5d03b829fe4fff8ff794304db14c5fb7ae140d8d5308814a",
          "sha256": "bdd585b4b24f6137facec46c03d04af540e2ef689d1aa883d5c283033428a812",
          "sha1": "1457a290c3f25b8e8f30b1587b721782ec1b8e26",
          "md5": "93e49a23b2affe259861085e62d8b235"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "data-access",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "remote-data",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "local-data",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sensor-data",
          "version": {
            "requires": "1.9.0-rc.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.9.0-rc.3.aar",
          "size": 1776133,
          "sha512": "230e5c367bc5edd24ac7d8e6579615f7c13e550bc84f50d832e1d66809e48bd3b4708d94ff9bc9fe5d03b829fe4fff8ff794304db14c5fb7ae140d8d5308814a",
          "sha256": "bdd585b4b24f6137facec46c03d04af540e2ef689d1aa883d5c283033428a812",
          "sha1": "1457a290c3f25b8e8f30b1587b721782ec1b8e26",
          "md5": "93e49a23b2affe259861085e62d8b235"
        }
      ]
    }
  ]
}
