{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.8.0-rc.1/sdk-1.8.0-rc.1.module",
    "group": "com.loopmediagroup.client",
    "module": "sdk",
    "version": "1.8.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "cb7rwvnvdngozm5mnfpjsxlmeq"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.8.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.8.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.8.0-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.8.0-rc.1.aar",
          "size": 1750115,
          "sha512": "5ad9e2ee6888c7e5fd1aa71bc4ae1241fe53dc6cc1c6bacbea4f18458a6066b94ac1497808baba959be6eb733844e4d1b591ae652de933e2f56455efa4cb7ccb",
          "sha256": "4bb12438bef571642257c16db0d385b1d83cc2ea302604cbe2462a3106df7f61",
          "sha1": "206424c119d1f063b575ea47636c9dfd90843e55",
          "md5": "4147a6f314cf1e096932c9dd1a21aa96"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "common",
          "version": {
            "requires": "1.8.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "domain",
          "version": {
            "requires": "1.8.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "analytics",
          "version": {
            "requires": "1.8.0-rc.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "data-access",
          "version": {
            "requires": "1.8.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "remote-data",
          "version": {
            "requires": "1.8.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "local-data",
          "version": {
            "requires": "1.8.0-rc.1"
          }
        },
        {
          "group": "com.loopmediagroup.client",
          "module": "sensor-data",
          "version": {
            "requires": "1.8.0-rc.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-release.aar",
          "url": "sdk-1.8.0-rc.1.aar",
          "size": 1750115,
          "sha512": "5ad9e2ee6888c7e5fd1aa71bc4ae1241fe53dc6cc1c6bacbea4f18458a6066b94ac1497808baba959be6eb733844e4d1b591ae652de933e2f56455efa4cb7ccb",
          "sha256": "4bb12438bef571642257c16db0d385b1d83cc2ea302604cbe2462a3106df7f61",
          "sha1": "206424c119d1f063b575ea47636c9dfd90843e55",
          "md5": "4147a6f314cf1e096932c9dd1a21aa96"
        }
      ]
    }
  ]
}
